# This file is part of the BenGorFile library.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

BenGor\File\Domain\Model\FileId:
    type: embeddable
    id:
        id:
            type: string
            length: 36
            column: id
